name: medicall
description: "Find The Right Emergency Room Right Now."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1  # Explicitly specify version 2.5.0 (instead of the latest 2.12.0)
  geolocator: ^14.0.0
  geocoding: ^2.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.2.1  # Added: dotenv package
  url_launcher: ^6.2.5  # Added: for opening browser links
  provider: ^6.1.1  # State management
  flutter_secure_storage: ^9.2.4  # Sensitive data storage
  app_links: ^3.0.0 
  http: ^1.3.0  # HTTP request handling
  uuid: ^4.5.1
  # Added: package for cookie management
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  # Added: package for settings storage
  shared_preferences: ^2.2.2

  # Added: Mapbox Navigation
  flutter_mapbox_navigation: ^0.2.2
  # mapbox_maps_flutter: ^1.4.0

  intl: ^0.20.2  #
  lottie: ^3.3.1
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env  # Added: .env file
    - assets/images/
    - assets/images/ambulance.png
    - assets/images/google_logo.png
    - assets/images/logo_white.png
    - assets/images/logo_color.png
    - assets/images/campaign_thumbnail.png
    - assets/images/ambulance-car-for-map.png
    - assets/images/location_pin.png
    
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
