# Uncomment this line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'             # 최소 타깃 14.0으로 상향

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Google Maps and utils
  pod 'GoogleMaps', '8.4.0'  # 8.4.0으로 변경 (google_maps_flutter_ios가 요구하는 최소 버전)
  pod 'Google-Maps-iOS-Utils', '5.0.0'
  
  # Mapbox SDKs: 버전 호환성 조정
  # pod 'MapboxNavigation', '2.14.0'       # 이 버전 유지
  # pod 'MapboxMaps', '10.14.0'            # 10.10.0에서 10.14.0으로 변경 (MapboxNavigation 2.14.0이 요구하는 버전)
  # pod 'MapboxCommon', '23.2.0'           # 이 버전 유지
  # pod 'MapboxCoreMaps', '10.14.0'        # 10.10.0에서 10.14.0으로 변경 (Maps와 일치)
  # pod 'MapboxCommon',     '23.6.0'
  # pod 'MapboxCoreMaps',   '10.14.0'
  # pod 'MapboxMaps',       '11.12.0-rc.1'
  # pod 'MapboxNavigation', '2.19.0'
  # pod 'MapboxMobileEvents', '1.0.8'      # 이 버전 유지
  # pod 'MapboxCommon',     '24.12.0-rc.1'
  # pod 'MapboxCoreMaps',   '11.12.0-rc.1'
  # pod 'MapboxMaps',       '11.12.0-rc.1'
  # pod 'MapboxNavigation', '2.19.0'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# MapboxMaps만 소스에서 직접 빌드하게 설정
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('MapboxMaps')
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # 최소 iOS 버전 설정 
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # 심볼릭 링크 관련 설정 추가
      config.build_settings['CLANG_MODULES_AUTOLINK'] = 'YES'
      
      # 프레임워크 검색 경로 추가
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/GoogleMaps/Base/Frameworks', '${PODS_ROOT}/GoogleMaps/Maps/Frameworks']
    end
  end
end



