# Uncomment this line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'             # Minimum target version raised to 14.0

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Google Maps and utils
  pod 'GoogleMaps', '8.4.0'  # Changed to 8.4.0 (minimum version required by google_maps_flutter_ios)
  pod 'Google-Maps-iOS-Utils', '5.0.0'
  
  # Mapbox SDKs: Version compatibility adjustment
  # pod 'MapboxNavigation', '2.14.0'       # Keep this version
  # pod 'MapboxMaps', '10.14.0'            # Changed from 10.10.0 to 10.14.0 (version required by MapboxNavigation 2.14.0)
  # pod 'MapboxCommon', '23.2.0'           # Keep this version
  # pod 'MapboxCoreMaps', '10.14.0'        # Changed from 10.10.0 to 10.14.0 (matches Maps version)
  # pod 'MapboxCommon',     '23.6.0'
  # pod 'MapboxCoreMaps',   '10.14.0'
  # pod 'MapboxMaps',       '11.12.0-rc.1'
  # pod 'MapboxNavigation', '2.19.0'
  # pod 'MapboxMobileEvents', '1.0.8'      # Keep this version
  # pod 'MapboxCommon',     '24.12.0-rc.1'
  # pod 'MapboxCoreMaps',   '11.12.0-rc.1'
  # pod 'MapboxMaps',       '11.12.0-rc.1'
  # pod 'MapboxNavigation', '2.19.0'

  # Mapbox compatible version reset 25.5.5
  pod 'MapboxMaps', '10.4.0'          # Using Turf 2.8.0
  pod 'MapboxDirections', '2.12.0'     # Turf 2.7.0 -> 2.8.0 compatible version
  pod 'MapboxNavigation', '2.11.0'     # Latest stable version
  pod 'Turf', '2.7.0'                 # Version fixed
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# pre_install do |installer|
#   installer.pod_targets.each do |pod|
#     if pod.name.eql?('MapboxMaps')
#       def pod.build_type;
#         Pod::BuildType.static_library
#       end
#     end
#   end
# end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['SWIFT_VERSION'] = '5.5'
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
#       config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= [
#         '$(inherited)',
#         '${PODS_ROOT}/MapboxMaps',
#         '${PODS_ROOT}/MapboxNavigation'
#       ]
#     end
#   end
# end


# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
    
#     target.build_configurations.each do |config|
#       # minimum iOS version
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
#       # symbolic link related settings
#       config.build_settings['CLANG_MODULES_AUTOLINK'] = 'YES'
      
#       # add framework search path
#       config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/GoogleMaps/Base/Frameworks', '${PODS_ROOT}/GoogleMaps/Maps/Frameworks']
#     end
#   end
# end




post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force Swift 5.5 setting
      config.build_settings['SWIFT_VERSION'] = '5.5'
      
      # Expand framework search paths
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= [
        '$(inherited)',
        '${PODS_ROOT}/MapboxMaps',
        '${PODS_ROOT}/MapboxNavigation'
      ]
      
      # Xcode 15 compatibility settings
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  flutter_env_plugin_path = File.join(Dir.pwd, '.symlinks', 'plugins', 'flutter_env_native', 'ios', 'setup_env.sh')
  root_dir = File.expand_path('..', Dir.pwd)
  system("sh \"#{flutter_env_plugin_path}\" \"#{root_dir}\"")
end
