name: medicall
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1  # 버전을 2.5.0으로 명시적 지정 (최신 2.12.0 대신)
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0  # 추가: dotenv 패키지
  url_launcher: ^6.2.5  # 추가: 브라우저 열기를 위한 패키지
  provider: ^6.1.1  # 상태 관리
  flutter_secure_storage: ^8.0.0  # 민감 정보 저장
  uni_links: ^0.5.1  # 딥링크 처리
  http: ^1.3.0  # HTTP 요청 처리
  
  # 쿠키 처리를 위한 패키지 추가
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  
  # WebView 추가
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.15.0
  # 웹뷰 쿠키 관리
  webview_cookie_manager: ^2.0.6

  # 설정 저장을 위한 패키지 추가
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env  # 추가: .env 파일
    - assets/images/
    - assets/images/ambulance.png
    - assets/images/google_logo.png
    - assets/images/logo_white.png
    - assets/images/campaign_thumbnail.png
