name: medicall
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0  # 버전을 2.5.0으로 명시적 지정 (최신 2.12.0 대신)
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0  # 추가: dotenv 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env  # 추가: .env 파일
    - assets/images/
    - assets/images/ambulance.png
    - assets/images/google_logo.png
    - assets/images/logo-white.png
