name: medicall
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.5  # Downgraded to be compatible with google_maps_webservice
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4  # Downgraded from 6.1.0 to be compatible with http 0.13.5
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  provider: ^6.1.1
  flutter_secure_storage: ^8.0.0
  uni_links: ^0.5.1
  flutter_mapbox_navigation: ^0.2.2
  path_provider: ^2.1.0  # 파일 경로 접근을 위해 추가
  
  # 쿠키 처리를 위한 패키지 추가
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  
  # WebView 추가
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.15.0
  # 웹뷰 쿠키 관리
  webview_cookie_manager: ^2.0.6

  # 설정 저장을 위한 패키지 추가
  shared_preferences: ^2.2.2
  
  # 추가: http 패키지 호환성을 위한 패키지
  http_parser: ^4.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env  # 추가: .env 파일
    - assets/images/
    - assets/images/ambulance.png
    - assets/images/google_logo.png
    - assets/images/logo_white.png
    - assets/images/campaign_thumbnail.png
