# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter with the suggested version for Dart SDK 3.7.2+
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Updated Flutter version (Including Dart SDK 3.7.2+)
          channel: 'stable'

      # CI .env file generation
      - name: Create dummy .env file
        working-directory: ./medicall
        run: |
          echo "GOOGLE_MAPS_API_KEY=dummy_key_for_ci" > .env
          echo "API_BASE_URL=https://example.com" >> .env

      - name: Install dependencies
        working-directory: ./medicall
        run: flutter pub get

      # keep the tests
      - name: Run tests
        working-directory: ./medicall
        run: flutter test
