# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter instead of just Dart with a newer version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # 업데이트된 Flutter 버전 (Dart SDK 3.7.2 이상 포함)
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./medicall
        run: flutter pub get

      # Consider using Flutter-specific commands for analysis and testing
      - name: Analyze project source
        working-directory: ./medicall
        run: flutter analyze

      - name: Run tests
        working-directory: ./medicall
        run: flutter test
